name: Nimbus_macOS
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - hdf5
  - numpy
  - pip:
      - tensorflow==2.13.*
      - tensorflow-macos==2.13.*
      - tensorflow-metal==1.0.1
      - .
