name: Nimbus_macOS
channels:
  - defaults
  - conda-forge
dependencies:
  - cudatoolkit=11.8.0
  - python=3.11
  - pip
  - hdf5
  - numpy
  - pip:
      - nvidia-cudnn-cu11==8.6.0.163
      - tensorflow==2.13.*
      - tensorflow-macos==2.13
      - tensorflow-metal==1.0.1
      - .
